### ISSUE TITLE
Phenotypes appearing more than once in the predefined list don't show up in the selection summary on re-edit

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1049]
To reproduce:
- go to the administration, _Phenotypes displayed by default_
- select the _Detailed physical phenotype configuration_, save
- create a new patient
- select _Broad finger_ and _Arachnodactyly_ from _Upper extremities_
- save
- edit
- in the selection summary, only _Broad finger_ shows up, although _Arachnodactyly_ is selected (`Y`), and it shows up in view mode as well

**Comment by allasm** [comment]
I think Anton has a point, since his example phenotype ("arachnodactyly") describes long fingers, which in theory can be applied separately to lower and upper limbs. And if the doctor meant to show long fingers on the lower limbs, he/she may be surprised if after a reload it will be checked in the upper limbs section.
