### ISSUE TITLE
Add more fields for candidate genes

### ISSUE THREAD

**Issue by marta-** [phenotips/phenotips#1149]
- Transcript Id (String)
- Interpretation(ACMG category): {Pathogenic, Likely Pathogenic, Variant of Unknown Significance, Likely Benign, Benign}
- CDNA change code:  c.X123Y where X,Y are from {A,C,G,T}, 123 is any number
- Protein change code: p.X123Y where X,Y are one of 20 amino acids
- Inhertiance {denovo, maternal, paternal,unknown}
- Validated {yes,no}
- Genomic Position: chromosome, position, build

**Comment by buske** [comment]
Included in Mike's Iowa notes: "for candidate gene add mutation".

**Comment by buske** [comment]
Mutalyzer might be helpful if we want to validate the field: 
https://www.mutalyzer.nl/name-checker?description=AB026906.1%3Ac.274G%3ET
https://www.mutalyzer.nl/webservices

E.g.:
https://mutalyzer.nl/json/checkSyntax?variant=AB026906.1:c.274del

**Comment by veronikaslc** [comment]
Plan for implementation:

- HGVS text field, validated by mutalyzer, instead of:
  - Transcript Id (String)
  - CDNA change code: c.X123Y where X,Y are from {A,C,G,T}, 123 is any number
  - Protein change code: p.X123Y where X,Y are one of 20 amino acids
  - Genomic Position: chromosome, position, build
- Interpretation(ACMG category): {Pathogenic, Likely Pathogenic, Variant of Unknown Significance, Likely Benign, Benign} (V.U.S. is default)
- Inhertiance {denovo, maternal, paternal,unknown} (options are actually HPO terms in backend)
- Validated {yes,no}
