### ISSUE TITLE
Selecting NA for a phenotype appearing more than once, does not select NA for all

### ISSUE THREAD

**Issue by antonkatz** [phenotips/phenotips#1350]
Example:
`Arachnodactyly` appears under both `Lower` and `Upper` extremities.
Selecting `Y` or `N` for either selects the same for the other.
But selecting `NA` does not have the same effect

**Comment by allasm** [comment]
Hmm, accordig to wikipedia "Arachnodactyly ("spider fingers") or achromachia, is a condition in which the fingers are abnormally long and slender in comparison to the palm of the hand.". 

So in this case doesn't it make sense to have arachnodactyly of upper fingers be separate from arachnodactyly of lower fingers, since the two conditions don't necessarily come together?

**Comment by antonkatz** [comment]
That's correct. Found this issue while working on that one.

**Comment by sdumitriu** [comment]
The semantic correctness of the term placement is not relevant, the issue still happens.

The problem with using two terms in two different places, although not really correct, is that some users do want a term to appear in different body parts, although HPO does not yet offer two terms. Hopefully in the future HPO should have all the needed terms, so we wouldn't have to use any of them more than once, but until that day we still have to make sure our code works correctly even with bad mapping files.

**Comment by allasm** [comment]
As a side note, how is split into categories work, how do we decide which terms go into which categories? And shouldn't we just collect all such terms and contact (Peter Robinson?) and ask to adjust it? Like this "arachnodactyly" term really make much less sense without specifying which set of fingers is affected
