### ISSUE TITLE
Patient has hidden candidate gene?

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1406]
Patient P0000056 has a candidate gene of POLG. However, when JSON exporting, two candidate genes are listed, POLG and POLG1. This was discovered because the patient did not show any candidate genes, but the POLG1 appeared in the JSON export. @bgallinger then added the POLG candidate gene with the same description. Presumably it should be POLG1, but it's unclear how this second candidate gene is hiding.

**Comment by allasm** [comment]
I checked the patient and (I don't know why) but it has one "InvestigationClass" POLG1 and one "RejectedGenesClass" POLG. I don't know off the top of my head what InvestigationClass is (or used ot be if it is deprecated)

https://phenomecentral.org/edit/data/P0000056?editor=object:
- Objects of type PhenoTips.InvestigationClass (1)
InvestigationClass 0: POLG1
- Objects of type PhenoTips.RejectedGenesClass (1)
RejectedGenesClass 0: POLG

**Comment by sdumitriu** [comment]
`InvestigationClass` is the correct one, it's supposed to store candidate genes. Except that it has a `type` property which was used initially to distinguish between molecular and genetic tests. The _Candidate Genes_ section shows only the `molecular` type, but the patient has a `genetic` investigation, that's why it doesn't show up in the UI. The export seems to ignore the type and lists all the `InvestigationClass` objects. Ways to solve this:

1. Do we want to only export `molecular` candidates?
2. Do we want to ignore the type and display all candidates in the patient record?

**Comment by buske** [comment]
Bump. This is causing problems with matchmaking, e.g. for https://phenomecentral.org/P0000056.

**Comment by sdumitriu** [comment]
@buske See my questions above. I still need answers.

**Comment by buske** [comment]
@sdumitriu Sorry, I'm not sure I understand the differences and tradeoffs enough to answer your questions. It seems like the solution in this particular case might be to move all `genetic` `InvestigationClass` objects over to `molecular` on PhenomeCentral, or just delete them entirely since they're deprecated?
