### ISSUE TITLE
Finer grained measurement evaluation, using the age in days instead of months

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1428]
Compute based on `365.25/12 = 30.4375` days/month.

**Comment by sdumitriu** [comment]
Remaining bug:

- create a new patient
- set the date of birth at `2015-02-01`
- set the gender to `Male`
- add a new measurement set
- set the measurement date at `2015-02-15`
- set the weight at `3.5`
- the weight is evaluated at `31st pctl (-0.49SD)`
- save
- in view mode the weight is evaluated at `62nd pctl (+0.31SD)`, since the recorded age is 0 months.

**Comment by sdumitriu** [comment]
Previous bug is now fixed. Remaining bug: the growth chart still displays month-based evaluations.

**Comment by mjshepherd** [comment]
Just to add to that. If the charts have show a finer grain then the x-axis should be more accurate. Right now if a patient is one month old then the data point on the chart displays between the 1 and 2 month vertical gridline.
