### ISSUE TITLE
Synchronize patient data between Phenotips and pedigree editor

### ISSUE THREAD

**Issue by allasm** [phenotips/phenotips#1459]
When proband data is changed in the pedigree editor the changes should propagate to PhenoTips patient. Same should happen to all other nodes which are linked to a patient (see #1146).

Potential problems\ambiguities:
- what about data represented a bit differently in PhenoTips and the editor, e.g. PhenoTips has both maternal and paternal ethnicity fields, while the pedigree editor has only one "ethnicity" field. Also, should maternal and paternal ethnicities propagate to the parent nodes or not?
- PhenoTips auto-populates certain fields based other fields (e.g. macrocephaly based on measurements), which pedigree editor does not. Would this result in possibly inconsistent data?

**Comment by sdumitriu** [comment]
> What about data represented a bit differently in PhenoTips and the editor, e.g. PhenoTips has both maternal and paternal ethnicity fields, while the pedigree editor has only one "ethnicity" field. Also, should maternal and paternal ethnicities propagate to the parent nodes or not?

Both tools should use the same type/format for data. It's a bit difficult to properly handle ethnicities, since the patient record records the maternal and paternal ethnicities, while the pedigree node records the patient's mixed ethnicity. We could split the ethnicity in the pedigree as well, but that wouldn't make much sense: we can record explicitly the father's and mother's ethnicities in their respective nodes. Another idea is to copy the ethnicities of the parent nodes into the patient record, but then what would happen to the data entered in the proband itself? Maybe add a third ethnicity field in the patient record, as an alternative to the two separate fields? If the clinician has the parent's ethnicities, then she fills in the two m/p fields, otherwise she fills in the mixed field. Then we can also synchronize the data between the pedigree and the patient record.

> PhenoTips auto-populates certain fields based other fields (e.g. macrocephaly based on measurements), which pedigree editor does not. Would this result in possibly inconsistent data?

This example is not quite valid, because the pedigree doesn't have measurements. And I can't find a valid example...

**Comment by allasm** [comment]
> And I can't find a valid example...

Thats good. I do not know all the places where data is auto-populayted, so wanted to put the comment in so that this issue is reviewed before implementation. If you say there is no such thing it means we'll have one less problem :)
