### ISSUE TITLE
Include pregnancy as option from 'new child' click

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1483]
Rather than creating a new child, editing details, and selecting 'Unborn'.

Suggested by Courtney.

**Comment by sdumitriu** [comment]
@danielpgross See Fig. 1 in the [ Standardized Pedigree Nomenclature](http://geneticcounselingtoolkit.com/cases/pedigree/Bennett%20JGC%202008%20-%20Standardized%20Human%20Pedigree%20Nomenclature%20-%20Update%20and%20Assessment%20of%20the%20Recommendations%20of%20the%20National%20Society%20of%20Genetic%20Counselors.pdf) for information on standard symbols.

**Comment by danielpgross** [comment]
I'm assuming that in most cases the gender of the pregnancy is unknown, so 
- the default pregnancy gender should be unknown
- it's not necessary to provide the ability to choose the pregnancy's gender in the 'new child' popup

Regarding the symbol for this button, I prototyped two options:
- a diamond with a 'P' inside it: 

![pedigree_editor___phenotype_database](https://cloud.githubusercontent.com/assets/4006062/7027174/228c7f06-dd1c-11e4-9b0d-e2dae26a3216.png)
- just a 'P':

![pedigree_editor___phenotype_database](https://cloud.githubusercontent.com/assets/4006062/7027236/7b6353d4-dd1c-11e4-9268-42169b9d39ad.png)

I think the second option is better because it's simpler and a lot more readable. The "unknown gender" conveyed by the diamond is not really necessary anyway because that information will likely be assumed by the user and will be clear after the button is clicked.

**Comment by marta-** [comment]
@bgallinger Please see Daniel's comment on this issue and help us decide if the P symbol without a diamond is clear enough for the "pregnancy" button in the pedigree editor. Thanks!

**Comment by bgallinger** [comment]
Although option 2 is more readable, you need to use option 1 (the diamond with the P inside it) as this is standard pedigree nomenclature and no one annotates a pregnancy with just the letter P. If gender is known, you should be able to show a circle or a square with the letter P inside

**Comment by marta-** [comment]
Thanks Daniel and Bailey. As the gender is unknown, we will use the diamond with P inside.

**Comment by danielpgross** [comment]
Ok, thank you.
