### ISSUE TITLE
Standard deviation labels for birth weight are incorrect

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1522]
Current labels are incorrect:
- "Small for gestational age (<-2SD)" (defn: Birth weight less than 10th percentile)
- "Large for gestational age (>+2SD)" (defn: Birth weight > 90th percentile)

However, +/- 2SD is the threshold used for things that are in the most extreme 3% (e.g. 'Birth length less than 3rd percentile' is displayed as 'Small birth length (<-2SD)'), and conforms to a normal distribution. A more accurate threshold would be 1.3 SD, which is actually quite a large difference.

**Comment by sdumitriu** [comment]
The percentiles are not a very precise unit of measurement, since they depend on what is being considered as the population. SGA/LGA are defined based on all births, while the WHO data set that we're using is based on __healthy__ children, so most of the SGA/LGA children are already excluded from these charts.

These terms are sometimes defined as <2.5kg (low birth weight) and >4kg (macrosomia), which actually translates into 3%/-1.84SD and 91%/+1.31SD respectively. The +-2SD range hits at 2.437 and 4.395kg for males, 2.352 and 4.223 for females.

So, what do you propose that we do, given that the definition and the chart data are not compatible?

1. use the 10%/90% both in the label and in the cutoff, in which case we'll overdiagnose many healthy babies
2. use the 10%/90% in the labels, but either keep using 2SD or change to 2.5/4.0kg as the cutoff, in which case people will see a kid in the 3rd percentile that isn't labeled with LGA, which is confusing
3. ask @pnrobinson to change the definition so that it uses kgs, but then the definition will be unfamiliar to most clinicians, and won't take into account the _gestational age_ part of the label
4. find another data set for measurements (not again...) which includes all children, not just the healthy ones, so that the definition and the charts match
5. don't change anything

**Comment by buske** [comment]
Measuring with SDs is also imprecise in exactly the same way, and kg isn't appropriate because the threshold is subpopulation-dependent, no?

I would say that we should do our best to follow the spirit of the HPO term, meaning having cutoffs at roughly 10%/90% of all births. Given that our underlying measurements are biased, we should adjust as best we can, and use SD thresholds that result in a similar kg cutoff. I would therefore actually suggest:

  **2**. Use an underlying threshold that results in appropriate classifications given our biased measurements. I'd suggest -1.85 SD / +1.31 SD for now (since that can take into account the gestational age, once we have pre-term data). Agreement with a chart isn't necessary for now since we don't have a pre-term chart, but regardless I'd suggest having those labels be the proper definitions so they are valid guides for doctors, and having the classifications be valid for doctors, despite any disagreements between the two. Hopefully #1523 should help some. Alternatively, if this causes problems, I'd remove these SD labels entirely and let users look up the full details if they want to know the formal definitions.
