### ISSUE TITLE
Fuzzy date selector does not require year/month to specify day

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1538]
The fuzzy date selector for DOB and DOD does not require that year be specified to enter the month, or that year/month be specified to enter the day. If you specify year and day, the day gets silently deleted on the next save.

Browser: Firefox on Mac

**Comment by buske** [comment]
I know this (at least used to) be the case on the pedigree side, but it isn't working that way on the patient record side.

**Comment by sdumitriu** [comment]
This is kind of intentional, since the date format can be changed to d-m-y or m-d-y, in which case disabling the first inputs until a year is selected would be counterintuitive.

**Comment by allasm** [comment]
I partially got around this in pedigree editor (which supports only two formats as of now) by checking if format is yyyy-mm-dd and blocking more specific input fields until more generic are entered, and allowing any inputs in any order otherwise. Maybe we can do this on the patient page as well, to at least cover 50% of use cases (don't think we can do much when doctors insist that they start from the day since they are given dates in dd-first format)
