### ISSUE TITLE
Vocabularies should auto-generate their Solr configuration at startup

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1640]
This is needed so that new ontologies can be easily installed as extensions, without the need to manually modify the Solr configuration on disk.

At startup, an ontology component copies the configuration from inside the jar into the solr directory, and calls `org.apache.solr.core.CoreContainer.create(CoreDescriptor)` to register it.

**Comment by veronikaslc** [comment]
To sum up what has to be done:
1. Instead of having all the configuration files for the ontologies in resources/solr-configuration, each vocabulary should have its own configuration (but not the actual index files) in its src/main/resources 
2. Implement SolrVocabularyResourceManager.java initialize() method to prepare and register the core, if it doesn't exist already, by: 
 -- Copy the configuration from inside the jar into the solr directory <permanent directory>/solr/<core name>
 -- Call org.apache.solr.core.CoreContainer.create(CoreDescriptor) to register it.
