### ISSUE TITLE
No warning message when trying to change patient gender in pedigree

### ISSUE THREAD

**Issue by JKereliuk** [phenotips/phenotips#1641]
If patient gender is specified in patient data, no matter what it is set to in the pedigree the patient data selection will always override it.
Instead, it might be good to provide warnings when a user tries to input data in the pedigree that contradicts the patient data and ask if they want to override.

**Comment by allasm** [comment]
After "family studies" branch is merged in the data will be propagated from pedigree back to the patient, so that if gender is changed in pedigree it will be changed in the patient as well (it is not the case right now). When this happens, we probably don't need any warnings, or we'll have to warn for all pedigree edits
