### ISSUE TITLE
Using two consecutive dashes -- in the patient's identifier field will display it striked out in view mode

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1729]

**Comment by mjshepherd** [comment]
This seems to happen in all text fields. Usually not noticed but I have seen text contain something like "-->" which ends up getting crossed out

**Comment by sdumitriu** [comment]
Yes, other fields must be fixed as well.

**Comment by danielpgross** [comment]
This is actually true for any XWiki wiki syntax, e.g. ```**bold**``` will produce bold text.

**Comment by danielpgross** [comment]
It turns out that this issue is quite broad and comes down to the use of the ```display()``` method on ```com.xpn.xwiki.api.Document``` objects inside velocity macros across the application. ```display()``` renders XWiki syntax before returning the string, leading to the behaviour described here. A simple solution is to instead of using ```display()```, use the ```getValue()``` method, which does not render wiki syntax before returning.

Uses of ```display()``` occur in lots of different places, and I don't think fixing them will be a simple matter of search/replace, since in some places wiki markup rendering is actually the desired behaviour.
```
Searching 242154 files for ".display("
...
1023 matches across 135 files
```

For now I'll correct the instance in the patient identifier field, which is actually generated by a patient sheet macro, so it will apply to some other fields as well.

**Comment by danielpgross** [comment]
To be clear, I'm leaving all fields other than the patient identifier field beyond the scope of this issue. Fixing "all fields" will require more of an audit-type process that looks at the use of ```display()``` throughout the application and determines an appropriate correction for each case.
