### ISSUE TITLE
Removing one phenotype eliminates ability to match patients with otherwise very similar phenotypes

### ISSUE THREAD

**Issue by CourtneyHum** [phenotips/phenotips#1748]
Issue #1: Two patients in PhenomeCentral (P0001084 and P0001768) with similar phenotypes show up as 56% match. Remove "ataxia" from P0001768 and the system no longer matches them, despite the fact that other terms such as "gait ataxia" and "truncal ataxia" are still present. 

Issue #2: Why are they only a 56% match? I would expect it to be much higher.

**Comment by buske** [comment]
Issue 1: I can't think of any reason why this would happen. Looks like it might be a seeding issue, but they have so many other terms in common that's unlikely. It could be a bug in the scoring, since it's an odd case of having the ancestor "ataxia" along with descendant terms. @tmarathe, @DeanWay, @JKereliuk want to create a unit test for this in patient-network with mock patients?

Issue 2: That's a pretty strong match with our current scoring scheme, but the amount the two patients overlap is still 56% in the way we currently measure it.

**Comment by CourtneyHum** [comment]
So if I have a user asking me when they should consider inquiring about a potential match...I should say that 56% is strong enough to go for it?

**Comment by buske** [comment]
I would suggestion they always look at the details of the match and use that to determine whether or not to follow up, rather than the score. The score is useful for ranking the results, and for a rough measure of how much stronger the first matches than the second, for example. Perhaps we should hide the score like Google does?

**Comment by buske** [comment]
Potentially related to: https://github.com/phenotips/patient-network/issues/24

**Comment by buske** [comment]
Replaced by https://phenotips.atlassian.net/browse/PN-95
