### ISSUE TITLE
Parent terms are not selected when a nested nested term is checked/selected.

### ISSUE THREAD

**Issue by tmarathe** [phenotips/phenotips#1755]
Example:
![screen shot 2015-06-10 at 3 49 10 pm](https://cloud.githubusercontent.com/assets/9522666/8092631/0b25343a-0f89-11e5-8cf5-09beedad4e86.png)
![screen shot 2015-06-10 at 3 50 23 pm](https://cloud.githubusercontent.com/assets/9522666/8092632/0c70dd1c-0f89-11e5-800c-a739198fdaff.png)

When a specific phenotype is selected, should the more general parent terms also be automatically selected? This would affect OMIM search suggestions.

**Comment by marta-** [comment]
For phenotypes all parent categories are selected implicitly and participate in omim search suggestions and matchmaking. We just don't display them as selected.

However, for mode of inheritance we indeed don't select parents. This doesn't affect any functionality at the moment, because this info doesn't yet participate in searches.

**Comment by sdumitriu** [comment]
This is the intended behavior. We might want to highlight somehow the implicitly selected terms at some point, but that's not easy to do right now.
