### ISSUE TITLE
Add questions to "Diagnosis" section

### ISSUE THREAD

**Issue by kimsplinter** [phenotips/phenotips#1777]
Questions:
1. “Working Diagnosis” (format: ICD terms or OMIM terms)
a. “Caused by genetic mutation?” (options: “Yes”, “No”, “Unknown”)
b. “Reported in other individuals?” (options: “Yes”, “No”, “Unknown”)
2. “Confirmed Diagnosis” (format: ICD terms or OMIM terms)
a.“Caused by genetic mutation?” (options: “Yes”, “No”, “Unknown”)
b. “Reported in other individuals?” (options: “Yes”, “No”, “Unknown”)

**Comment by davidbernick** [comment]
Make sure that you roll these changes into UDN branch.

**Comment by CourtneyHum** [comment]
Hi @kimsplinter and @davidbernick , 

We're in the process of improving both the Genotype and the Diagnosis sections of PhenoTips and I think that our changes will address the issues you've raised. 

1. In the Genotype section there will be tables to enter each gene that has been tested. You can enter variants and list evidence such as "rare" "predicted pathogenic by in silico models" "reported in other individuals" "segregates with phenotype in family"

2. In the Diagnosis section there will be 
a) "Working Clinical Diagnosis" which we're hoping will be entered in Orphanet terms because unlike OMIM, they do not have to be down to the gene level.  
b) "Molecularly Confirmed Diagnosis" which will be OMIM terms. 

Let us know what you think

**Comment by kimsplinter** [comment]
@CourtneyHum that sounds great and will address the additions that we requested previously.
