### ISSUE TITLE
Selecting affected in radio buttons allows multiple choices

### ISSUE THREAD

**Issue by kereliuk** [phenotips/phenotips#1819]
The affected status is the orange background of the node.

We can choose a node to be pre-symptomatic and affected
![prenotaffected](https://cloud.githubusercontent.com/assets/9435736/8660187/682a9798-297d-11e5-84d3-93a430df7893.png)

We can also choose it to be pre-symptomatic and not affected by selecting the "Not affected" radio button and then switching to pre-symptomatic again.
![affectedandpre](https://cloud.githubusercontent.com/assets/9435736/8660188/69d39572-297d-11e5-8cd3-1dde1faf4223.png)

The radio button group should only allow one selection of these options and not multiple.
It appears that the only thing that gets rid of the affected status is explicitly selecting the "Not Affected" button once.

**Comment by allasm** [comment]
This is intended behaviour, though we can likely optimize it.

The thing to note is that disorders affecting the person are independent form the carrier status. E.g. someone may have no indicated disorders but still a carrier, or a few indicated disorders and a carrier. The unifying point is that "not affected" means "no disorders and no special carrier status". The "unifying" nature of "not affected" is what makes this radio behave as strange as it does.

So the way it works is once "carrier/presymptomatic/uncertain" is selected the corresponding symbol is added to the node. Independently of that, once "affected" is selected the person is given the unnamed "affected" disorder (this is done so that is someone is known to be affected it is on the legend and has at least one disorder, just - if only thing known is "affected" - disorder has no special name and is called "affected" and special yellow colour is used). In fact, if a blank new person is given a disorder using the selector below, the same thing would happen, just disorder name and colour would be different.

Now, once there is a person with any disorder(s), the status may be changed form simply "affected" to "carrier" and others. The person still retains all the disorders he or she has, including the "affected" one. It can either be manually removed using the "x" near the disorder selector, or by selecting "unaffected" which clears everything.

Any suggestions to improve this are welcome
