### ISSUE TITLE
phenotips alternatives

### ISSUE THREAD

**Issue by albodrug** [phenotips/phenotips#2923]
Hello PhenoTIPs team, 

Do you known of software that is still open source and free, and answers to the same needs as PhenoTIPs does? Unfortunately my team has no money to pay for the licence, but we could greatly benefit from something similar...

Best of luck, 
Alex

**Comment by buske** [comment]
Hi @albodrug, you're welcome to continue using and developing on the open-source version of PhenoTips. That hasn't changed, but all new development is being done on the commercial side, rather than the research team. One open-source and free solution to look into that can fill some of the same roles is RedCap.
